### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aforren1** [aforren1/sample-psychopy-exp#1]
- [ ] Generate trial table (with rotation) (10 trials?)
  - [ ] Single target
  - [ ] experiment state machine
      - [ ] Free response
      - [ ] Timed response
      - [ ] Pressured time
  - [ ] visuomotor rotation (encoded in trial table)
  - [ ] Velocity speed bar
